// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFVbCwYqAoeQe3hF0w5r88CZ1sxVsW80',
    appId: '1:266880203721:web:361127843c34d468774618',
    messagingSenderId: '266880203721',
    projectId: 'cn-call-3feb3',
    authDomain: 'cn-call-3feb3.firebaseapp.com',
    storageBucket: 'cn-call-3feb3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5DG15PiS7V1JAgsE819q7K10ger5e7wg',
    appId: '1:266880203721:android:7ab703344356210a774618',
    messagingSenderId: '266880203721',
    projectId: 'cn-call-3feb3',
    storageBucket: 'cn-call-3feb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC24gQLBCKWDrM4pUzwbPc7OaTf7kecP08',
    appId: '1:266880203721:ios:7a7667694887d2bb774618',
    messagingSenderId: '266880203721',
    projectId: 'cn-call-3feb3',
    storageBucket: 'cn-call-3feb3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC24gQLBCKWDrM4pUzwbPc7OaTf7kecP08',
    appId: '1:266880203721:ios:7a7667694887d2bb774618',
    messagingSenderId: '266880203721',
    projectId: 'cn-call-3feb3',
    storageBucket: 'cn-call-3feb3.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvFVbCwYqAoeQe3hF0w5r88CZ1sxVsW80',
    appId: '1:266880203721:web:0008c95ee578e811774618',
    messagingSenderId: '266880203721',
    projectId: 'cn-call-3feb3',
    authDomain: 'cn-call-3feb3.firebaseapp.com',
    storageBucket: 'cn-call-3feb3.firebasestorage.app',
  );
}
